[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm config set legacy-peer-deps true",
  "npm cache clean --force",
  "npm install --production --no-optional --ignore-scripts"
]

[phases.build]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "true"
MONGOMS_DISABLE_POSTINSTALL = "1"
